Semana10
FabianoCarregas/human-dev pull request #10
Opened 2022-04-20 12:58 UTC by FabianoCarregas

2022-04-20 21:47 UTC, jonilsonds9 requested changes

2022-04-20 21:47 UTC, jonilsonds9 commented on pom.xml
> +		</dependency>
Dá pra usar a versão, mas não vou cobrar aqui

2022-04-20 21:47 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/PublicController/CategoryControllerWeb.java
> +
Remover esse cara!

2022-04-20 21:47 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/dtos/publicLink/CategoryLinkDto.java
> +    }
Você tinha mudado esse cara não??

2022-04-20 21:47 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/Profile.java
> +    }
Precisa desse cara mesmo?

2022-04-20 21:47 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/subcategories/putSubcategories.jsp
> +                        <option value="${categoria.id}" ${categoria.name == subcategory.category.name ? 'selected' : ''}>${categoria.name}</option>
Cara melhor comparar com o `code` aqui

2022-04-22 23:54 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/dtos/publicLink/CategoryLinkDto.java
> +    }
mudei, mas ainda não comitei com a mudança!

2022-04-22 23:56 UTC, FabianoCarregas commented on src/main/webapp/WEB-INF/views/subcategories/putSubcategories.jsp
> +                        <option value="${categoria.id}" ${categoria.name == subcategory.category.name ? 'selected' : ''}>${categoria.name}</option>
bem observado!

2022-04-22 23:58 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/entities/Profile.java
> +    }
Não precisava, mas essa semana 11 vai precisar!

2022-04-23 00:12 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/dtos/publicLink/CategoryLinkDto.java
> +    }
https://github.com/FabianoCarregas/human-dev/commit/4c3293a7d9b11ab1a9ad591768870279781e2de9

2022-04-25 12:43 UTC, jonilsonds9 requested changes

2022-04-25 12:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/repositories/SubcategoryRepository.java
> +         ON c.id = s.category.id
Como você tá usando JPQL aqui não precisa desses ids, mas como funciona não vou cobrar, só que é bom saber, JPQL usa os objetos do Java, Native Query usa os campos diretamente como está no banco de dados.

2022-04-25 12:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +        CategoryLinkProjection category = categoryRepository.findCategoryByCodeAndActiveCourses(categoryCode);
Melhor esse método do Repository retornar um Optional, ai fica melhor e evita NPE.

2022-04-25 12:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/repositories/CategoryRepository.java
> +    CategoryLinkProjection findCategoryByCodeAndActiveCourses(String code);
Acho que varia mais sentido retornar um Optional, como falei no controller.

2022-04-25 12:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/repositories/SubcategoryRepository.java
> +         ON c.id = s.category.id
Esse não precisa mudar, só uma observação importante mesmo!

2022-04-25 13:05 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/repositories/SubcategoryRepository.java
> +         ON c.id = s.category.id
Preferi deixar certo pra usar como exemplo pra futuras consultas no meu repositório!

2022-04-25 13:06 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +        CategoryLinkProjection category = categoryRepository.findCategoryByCodeAndActiveCourses(categoryCode);
https://github.com/FabianoCarregas/human-dev/pull/10/commits/6eb18511c08eff6d331ffcf2b45a4b80128e4dca

2022-04-25 16:23 UTC, jonilsonds9 approved these changes

2022-04-25 16:30 UTC, fabiuhp approved these changes

2022-04-25 16:32 UTC, merged