Semana12
FabianoCarregas/human-dev pull request #12
Opened 2022-05-11 16:33 UTC by FabianoCarregas

2022-05-11 16:57 UTC, jonilsonds9 requested changes

2022-05-11 16:57 UTC, jonilsonds9 commented on pom.xml
> +			<optional>true</optional>
Sem esse cara funciona normal??

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +    }
Porque não usar o lombok aqui nos controllers também? Acho que é melhor pra não usar esse código Boilerplate

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/dtos/LoginForm.java
> +@RequiredArgsConstructor
Porque usou os dois tipos de contrutores? Acho que precisa usar um ou outro aqui...

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/dtos/api/CategoryDtoApi.java
> +@Setter
Você usar todos os setters nesse Dto? Se sim, então mantém, se não, coloca manualmente cada um

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/validators/CourseValidator.java
> +            }
Arrumar indentação, daqui pra frente vai ser muito importante isso, agora você ver e mexer muito código que outras pessoas fizeram, e é importante sempre manter as melhores práticas de indentação e também os espaços, tudo aqui que batemos bastante na tecla lá no começo do Level Up

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/resources/V2__humandev-new-data.sql
> +
Cara, renomeia esse arquivo, para dump ou algo do tipo, porque fica confuso, lendo o nome pensei que era mais uma migration!

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categories/postcategory.jsp
> +</templates:template-pageEnd>
Aqui como você não vai colocar nada dentro do `doBody` do `template-pageEnd`, você deve fechar na mesma linha, tipo:
```
<templates:template-pageEnd/>
```

2022-05-11 16:57 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categories/putCategories.jsp
> +</templates:template-pageEnd>
Mesma coisa que falei antes, tenta replicar em todos os casos que estão assim!

2022-05-11 18:37 UTC, FabianoCarregas commented on pom.xml
> +			<optional>true</optional>
Funcionou sem o <optional> tbm, dai eu tirei!

2022-05-11 18:37 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +    }
Boa !

2022-05-11 18:40 UTC, jonilsonds9 approved these changes

2022-05-13 15:26 UTC, fabiuhp approved these changes

2022-05-13 17:15 UTC, merged