Semana2
FabianoCarregas/human-dev pull request #2
Opened 2022-02-24 11:33 UTC by FabianoCarregas

Reader {categories, subcategories, courses};
HtmlWriter {categories, subcategories, courses};

2022-02-24 17:02 UTC, jonilsonds9 requested changes

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/application/Program.java
> +        ArrayList courses1 = new InstanceCourse().loadCourses(subcategories1, "/home/fabiano/Desktop/csv/Curso.csv");
Aqui não era melhor ter método estaticos? Acho que ficaria menos verboso

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/entities/Category.java
> +        this.code = code;      //exceptions
Porque esse comentário aqui?

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCategory.java
> +    public ArrayList<Category> loadCategory(String file) {
Poderia deixar estático e fazer isso nas outras classes também, acho que não precisamos ter uma instância dessa classe pra gente poder usar esse método.

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCategory.java
> +            System.out.println("err: " + e.getMessage());
Acho que aqui, deveria subir a exception diretamente pro usuário, tipo lançar uma `IllegalArgumentException` com uma mensagem indicando que o CSV está com erro.

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCategory.java
> +                        vect[2].equals("")?0:Integer.parseInt(vect[2]),
Colocar os espaços aqui, fica muito complicado de entender sem espaços, sempre quando usar ternário aplicar bem os espaços.

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCourse.java
> +    public ArrayList<Course> loadCourses(ArrayList<Subcategory> subcategories, String file) {
Deixar estático

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceSubcategory.java
> +    public ArrayList<Subcategory> loadSubcategory(ArrayList<Category> category, String file) {
Deixar estático

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCourse.java
> +        }
Ver o comentário anterior sobre exception

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCourse.java
> +    static Optional<Subcategory> findSubcategoryByCode(List<Subcategory> subcategories, String code) {
falta uma linha em branco aqui não?

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceCourse.java
> +                            possibleSubcategory.get());
Fiquei com dúvida aqui, se for null você espera que quebre lá no construtor dor curso é isso?

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceSubcategory.java
> +                        vect[2].equals("")?0:Integer.parseInt(vect[2]),
Adicionar espaços aqui

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceSubcategory.java
> +    static Category findCategoryByCode(List<Category> categories, String code) {
Linha em branco

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/readers/InstanceSubcategory.java
> +               .findFirst().orElse(null);
Acho que seria intessante colocar o `orElse()` no de curso também. Mas ainda tenho a dúvida lá

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/writers/filter/WriterFilters.java
> +    }
Boa!

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/writers/filter/WriterFilters.java
> +        return subcategoryList;
Legal, **não precisa mudar**, mas aqui você poderia retornar direto

2022-02-24 17:02 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/writers/Writer.java
> +                        """;
Ficou bem legal!

2022-02-24 22:23 UTC, jonilsonds9 approved these changes

2022-02-24 22:23 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/entities/Course.java
> +public class Course implements Comparable<Course> {
Você usa o `Comparable`?

2022-02-25 12:57 UTC, jonilsonds9 commented on src/br/com/alura/humanDev/entities/Course.java
> +public class Course implements Comparable<Course> {
É legal deixar o link do commit que você arrumou algum comentário sabe, facilita o review sabe

2022-02-25 13:32 UTC, FabianoCarregas commented on src/br/com/alura/humanDev/entities/Course.java
> +public class Course implements Comparable<Course> {
Boa, Maravilha!

2022-03-01 21:18 UTC, merged