Semana4
FabianoCarregas/human-dev pull request #4
Opened 2022-03-08 23:30 UTC by FabianoCarregas

PR semana 4

2022-03-09 16:30 UTC, jonilsonds9 requested changes

2022-03-09 16:30 UTC, jonilsonds9 commented on src/main/resources/db/sql/Subcategory.sql
> +'Builds e Controle de versão', 'builds-e-controle-de-versao', 1, 'As ferramentas mais utilizadas para desenvolvimento: controle de versão com Git e Github além de build da aplicação através de Maven.
Boa!!!

2022-03-09 16:30 UTC, jonilsonds9 commented on src/main/resources/db/sql/allTables.sql
> +CREATE TABLE Subcategory
Gostei!!

2022-03-09 16:30 UTC, jonilsonds9 commented on src/main/resources/db/sql/allTables.sql
> +);
Só uma coisa, porque alguns campos estão com as crases e outros não? Acho que seria melhor manter um padrão, talvez todos usando crase?

2022-03-09 16:30 UTC, jonilsonds9 commented on src/main/resources/db/sql/course.sql
> +`NAME`, `CODE_URL`, COURSE_TIME_HOURS, `STATUS`, TARGET_AUDIENCE, INSTRUCTOR, COURSE_DESCRIPTION, DEVELOPED_SKILLS, subcategory_id) VALUES (
Mesma coisa aqui, padrão, ou tudo com crase ou tudo sem

2022-03-09 16:30 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/Subcategory/SubcategoryTest.java
> +                () -> new Subcategory("Java", "java", 1, "curso", true, category));
Colocar esses valores como atributo da classe de teste, como você fez com o `category` na linha 15. Pra facilitar e evitar erros de escritas, deixar um unico ponto de falha.

2022-03-09 16:30 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/course/CourseTest.java
> +                        "Paulo", "Java jr", "OO", subcategory));
Mesma coisa que falei antes, colocar os valores como variaveis da classe e em cada teste mudar ou colocar manualmente o unico que você quer testar

2022-03-09 16:55 UTC, fabiuhp requested changes
Boa semana Fabiano!

2022-03-09 16:55 UTC, fabiuhp commented on src/main/java/br/com/alura/humanDev/entities/Category.java
> +
Poderia remover a linha.

2022-03-09 16:55 UTC, fabiuhp commented on src/main/resources/db/sql/allTables.sql
> +);
Se eu não me engano, a crase é utilizada em campos que podem ser palavras reservadas do mysql.

2022-03-09 19:21 UTC, jonilsonds9 commented on src/main/resources/db/sql/allTables.sql
> +);
Sim @fabiuhp, mas num era melhor colocar a crase em todos? Só pra manter um padrão

2022-03-09 19:26 UTC, FabianoCarregas commented on src/main/resources/db/sql/allTables.sql
> +);
Isso eu tinha colocado as crases somente nas palavras reservadas!
já coloquei em todas

2022-03-09 19:26 UTC, FabianoCarregas commented on src/main/resources/db/sql/course.sql
> +`NAME`, `CODE_URL`, COURSE_TIME_HOURS, `STATUS`, TARGET_AUDIENCE, INSTRUCTOR, COURSE_DESCRIPTION, DEVELOPED_SKILLS, subcategory_id) VALUES (
https://github.com/FabianoCarregas/human-dev/tree/semana4

2022-03-09 19:26 UTC, FabianoCarregas commented on src/test/java/br/com/alura/humanDev/course/CourseTest.java
> +                        "Paulo", "Java jr", "OO", subcategory));
resolvido

2022-03-09 19:27 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/entities/Category.java
> +
boa, resolvido!

2022-03-09 19:27 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/entities/Category.java
> +
https://github.com/FabianoCarregas/human-dev/tree/semana4

2022-03-09 19:43 UTC, jonilsonds9 approved these changes
Estou aprovando, porque o que passou foi uma crase que não faz tanta diferença, mas seria legal colocar!

2022-03-09 19:43 UTC, jonilsonds9 commented on src/main/resources/db/sql/course.sql
> +`NAME`, `CODE_URL`, COURSE_TIME_HOURS, `STATUS`, `TARGET_AUDIENCE`, `INSTRUCTOR`, `COURSE_DESCRIPTION`, `DEVELOPED_SKILLS`, `subcategory_id`) VALUES (
COURSE_TIME_HOURS deveria ter crase também

2022-03-09 19:49 UTC, FabianoCarregas commented on src/main/resources/db/sql/course.sql
> +`NAME`, `CODE_URL`, COURSE_TIME_HOURS, `STATUS`, `TARGET_AUDIENCE`, `INSTRUCTOR`, `COURSE_DESCRIPTION`, `DEVELOPED_SKILLS`, `subcategory_id`) VALUES (
🦅  Boa!

2022-03-10 15:26 UTC, fabiuhp approved these changes

2022-03-10 16:11 UTC, merged