Semana5
FabianoCarregas/human-dev pull request #5
Opened 2022-03-16 12:42 UTC by FabianoCarregas

review semana 5

2022-03-16 16:21 UTC, jonilsonds9 requested changes

2022-03-16 16:21 UTC, jonilsonds9 commented on human-dev.iml
> +    <orderEntry type="library" name="Maven: com.mchange:mchange-commons-java:0.2.16" level="project" />
Eu acho que esse arquivo não era pra tá aqui no GitHub, ele é mais pro intellij fazer as coisas dele e tal

2022-03-16 16:21 UTC, jonilsonds9 commented on pom.xml
> +        </dependency>
Tenta manter um linha em branco entre cada dependencia, ex:
```xml
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.28</version>
        </dependency>

        <dependency>
            <groupId>com.mchange</groupId>
            <artifactId>c3p0</artifactId>
            <version>0.9.5.4</version>
        </dependency>
```
Num projeto grande, ficar tudo junto, colado por dar brecha pra confusão.

2022-03-16 16:21 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/entities/dto/InsertCourse.java
> +public class InsertCourse {
Esse cara me parece ser apenas um DTO, então acho que deve ficar explicito no nome da classe, algo como `InsertCourseDTO` ou melhor `CourseDTO`, assim quem bater o olho no código já sabe que essa classe é apenas pra transferir os dados e não deverá conter todos os dados do curso em si.

2022-03-16 16:21 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/jdbc/query/CourseDAO.java
> +    public static int updateToActive() {
Aqui deveria ser `updateAllToActive`, assim sabemos que esse cara vai atualizar todos os cursos, vai que alguém usa esse cara sem saber disso? Pode dar ruim em produção

2022-03-16 16:21 UTC, jonilsonds9 commented on target/classes/db/sql/simpleQuery.sql
> +SELECT `name` FROM `Subcategory` WHERE `subcategory_description` = '';
Esse aquivo me parece tá repetido

2022-03-16 17:08 UTC, jonilsonds9 approved these changes

2022-03-16 17:09 UTC, FabianoCarregas commented on human-dev.iml
> +    <orderEntry type="library" name="Maven: com.mchange:mchange-commons-java:0.2.16" level="project" />
Bem observado, dei o rm la deu certo!

2022-03-16 17:10 UTC, FabianoCarregas commented on pom.xml
> +        </dependency>
https://github.com/FabianoCarregas/human-dev/blob/semana5/pom.xml

2022-03-16 17:12 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/entities/dto/InsertCourse.java
> +public class InsertCourse {
Eu tinha colocado CourseDTO depois mudei pra InsertCourse, mas o certo e mais descritivo realmente seria o "InsertCourseDTO".

2022-03-17 11:19 UTC, fabiuhp approved these changes

2022-03-17 16:09 UTC, merged