Semana6
FabianoCarregas/human-dev pull request #6
Opened 2022-03-23 12:51 UTC by FabianoCarregas

review 6

2022-03-23 18:44 UTC, jonilsonds9 requested changes
Alguns pontos gerais:

- Ter mais atencão aos commits, na verdade ao que vai entrar em cada commit, antes de fazer o commit verificar quais arquivos e quais as alterações, você pode ver usando o comando `git diff` e também diretamente no Intellij. Com isso vai evitar de subir coisas que não precisam, imagina num projeto real? Não seria nada legal.

- Outra coisa, antes de solicitar o review do PR, veja o PR, revise seu próprio PR pra ver se tá do jeitinho que você deseja e isso vai evitar mais comentários de *Request Changes*, essas são duas práticas que usamos na prática, assim facilita pra todo mundo, tanto pra você que fez o PR quanto pra quem vai revisar!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/application/TestDeleteCourse.java
> +    }
Boa!!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/application/TestUpdateStatus.java
> +        courseDAO.updateCourseStatusToPublic();
Esse método precisa ter o `all` no nome, porque parece que vai atualizar apenas 1 curso, mas na verdade vai alterar todos, acho que deveria ser `updateAllCoursesStatusToPublic()`

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +        this.em.getTransaction().commit();
Acho que seria bom ter um `try catch` aqui!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +        System.out.println("Course Id:" + id + " Created");
Mesma coisa que falei no outro, como podemos ter uma exception, deveriamos ter um `try catch` e ai facilita pra saber se deu algum problema! Aplica isso nos outros lugares também. Na minha cabeça todos os metodos dos DAOs deveriam ter um try catch

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +        this.em.getTransaction().commit();
try catch

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/SubcategoryDAO.java
> +        this.em.persist(subcategory);
try catch e commit

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/entities/Alternative.java
> +    }
Seria bom colocar um `@Deprecated` nesses construtores vazios, já que são apenas para uso da JPA e não queremos que ninguem use ele. Replicar para todos!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/reports/HtmlReport.java
> +    }
Acho que não precisa desse construtor já que o método dessa classe é estatico

2022-03-23 18:44 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/dao/CategoryDaoTest.java
> +    private EntityManager em ;
Remover espaço

2022-03-23 18:44 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/dao/CategoryDaoTest.java
> +        createCategory2();
Boa!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/dao/SubcategoryDaoTest.java
> +    }
Acho que precisa de mais testes, cada os cenários não felizes desses métodos?

2022-03-23 18:44 UTC, jonilsonds9 commented on src/test/java/br/com/alura/humanDev/entities/category/CategoryTest.java
> +//    }
Porque tá comentado? Descomenta, e roda e ver se tá passando!

2022-03-23 18:44 UTC, jonilsonds9 commented on target/classes/META-INF/persistence.xml
> +</persistence>
Tá subindo coisas da pasta target, precisa remover!

2022-03-23 18:44 UTC, jonilsonds9 commented on target/classes/db/sql/allTables.sql
>  `course_time_hours` SMALLINT UNSIGNED,
Mesma coisa, tá subindo coisas que não deveriam!

2022-03-23 18:44 UTC, jonilsonds9 commented on target/test-classes/META-INF/persistence.xml
> +</persistence>
Remover esse cara tá na target!

2022-03-23 18:44 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +        return findAllCourses();
Adicionar try catch e replicar também para os outros DAOs

2022-03-23 19:37 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/application/TestDeleteCourse.java
> +    }
:)

2022-03-23 19:38 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/application/TestUpdateStatus.java
> +        courseDAO.updateCourseStatusToPublic();
https://github.com/FabianoCarregas/human-dev/tree/semana6/src

2022-03-23 19:39 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +        return findAllCourses();
Adicionado!

2022-03-23 20:42 UTC, jonilsonds9 approved these changes
Estou aprovando mais deixei os dois comentários, se quiser mudar seria interessante, mas como é algo que não vejo como impeditivo para requisitar novas mudanças estou aprovando!

2022-03-23 20:42 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +        return null;
Falha minha aqui, peço desculpas, como aqui é um select apenas não precisa ter o try catch, poderia remover os `transaction` porque não precisamos de uma transação para fazer uma busca, pode voltar essa parte como tava antes se quiser, se não tudo bem. Falha minha, mil desculpas, nos casos que são apenas SELECT não precisa de transação, mas os DELETE, UPDATE ou SAVE precisa sim, pra garantir a confiabilidade dos dados.

2022-03-23 20:42 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +        return null;
Nesse caso, acho melhor você lançar uma `RuntimeException` no `catch` e ai não precisa ter o return `null`, mas não vou reprovar por isso, mas é interessante mudar!

2022-03-23 21:29 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +        return null;
Boa Jonilson, Sem problemas, vlew pelo toque!

2022-03-24 12:14 UTC, fabiuhp approved these changes

2022-03-24 14:58 UTC, FabianoCarregas commented
semana6

2022-03-24 14:58 UTC, merged