Semana7
FabianoCarregas/human-dev pull request #7
Opened 2022-03-30 12:01 UTC by FabianoCarregas

Servlets and Java script week seven

2022-03-30 16:43 UTC, jonilsonds9 requested changes
O seu javascript tá bem simples, e gosto assim, mas surgiu detalhes em outros PR, então acho bom indicar leitura para todos, sobre alguns pontos:

Sobre as aspas https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Strings#aspas_simples_x_aspas_duplas. Tudo bem usar aspas duplas, pórem se mantenha o uso, não use aspas duplas e simples misturadas, ou uma ou outra. Eu particularmente gosto de usar sempre simples, e em alguns linters também forçam a usar as simples.

Outro arquivo para leitura: https://blog.matheuscastiglioni.com.br/string-em-javascript-com-aspas-simples-ou-duplas/.

Também acho que seria até melhor usar `Template String`, acho que vocês ainda não viram, mas quando chegar a hora começem a usar, faz muita diferença.

Sobre usar ou não ponto e virgula ( ; ). O javascript é meio desmantelado, mas ainda podemos ter um código limpo e organizado, depende de nós...

Essa é uma polêmica grande e vem de muito tempo atrás, mas como o Douglas Crockford (veja o artigo de um dos bons instrutores de JS da alura nesse [link](http://cangaceirojavascript.com.br/javascript-ponto-virgula-polemica-atravessa-tempo/) para saber mais) falou, a omissão do ponto e vírgula tornaria nosso código um “insanely stupid code”.

2022-03-30 16:43 UTC, jonilsonds9 commented on META-INF/application.xml
> +</application>
Precisa mesmo desse arquivo?

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/application/TestInsertCourse.java
> +        Category category = new Category(null, "java", "code-j", 2, "desc",
Porque você trocou pra `null` aqui? Não entendi essa mudança.

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +            em.getTransaction().begin();
Aqui meio que tanto faz o uso do `this`, em código muito grandes e complexo é interessante manter o this, mas aqui fica bom, não precisa mexer!

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CourseDAO.java
> +            e.getMessage();
Porque uma `RuntimeException`? Não seria `Exception` mesmo que é mais generica, ou mesmo uma `SQLException`

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/servlet/ChangeStatusServlet.java
> +            throws IOException, ServletException {
Precisa desse `ServletException`?

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/servlet/PutCategoriesServlet.java
> +    @Override
Acho que poderia juntar esse `PutCategoriesServlet` com o `GetCategoryServlet`, já que é um conceito só, buscar e mostrar os dados da categoria na tela e depois alterar os dados.

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/servlet/PutCategoriesServlet.java
> +        CategoryDAO dao = new CategoryDAO(em);
Acho que esse cara deveria ser um atributo da classe. Veja bem, agora que você vai juntar esses dois (`PutCategoriesServlet` e `GetCategoryServlet`), você terá dois métodos que vão usar o DAO e não faz sentido repetir esse código pra instânciar o DAO.

Assim você vai usas tanto no `doGet` quanto no `doPost`, e não faz sentido replicar o mesmo código.

O que você poderia fazer era deixar o DAO como um atributo do objeto, assim poderia usar em ambos os métodos. E também acho válido replicar o mesmo comportamento para os outros Servlets mesmo que eles usem em apenas um método.

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/webapp/META-INF/MANIFEST.MF
> +Class-Path:
Acho que esse cara não precisa tá aqui no GitHub

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/webapp/categoriesList.jsp
> +        </tr>
Arrumar indentação aqui, mesmo o código JSP deve ter organização, assim facilita pra todo mundo...

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/webapp/scripts.js
> +var CHANGE_URL = "http://localhost:8080/changeCategoryStatus?id=";
Como falei, não precisa usar essa constante, pode usar a URL direto no código, já que você só usa em um único lugar.

2022-03-30 16:43 UTC, jonilsonds9 commented on src/main/webapp/scripts.js
> +    request.onload = function () {
Não precisa do espaço entre a palavra reservada `function` e o parentese:
```javascript
request.onload = function() {
```

2022-03-30 19:02 UTC, FabianoCarregas commented on META-INF/application.xml
> +</application>
removido

2022-03-30 19:03 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/servlet/ChangeStatusServlet.java
> +            throws IOException, ServletException {
https://github.com/FabianoCarregas/human-dev/blob/semana7/src/main/java/br/com/alura/humanDev/servlet/ChangeStatusServlet.java

2022-03-30 19:04 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/servlet/PutCategoriesServlet.java
> +        CategoryDAO dao = new CategoryDAO(em);
https://github.com/FabianoCarregas/human-dev/blob/semana7/src/main/java/br/com/alura/humanDev/servlet/GetAllCategoriesServlet.java

2022-03-30 19:04 UTC, FabianoCarregas commented on src/main/webapp/META-INF/MANIFEST.MF
> +Class-Path:
removido

2022-03-30 22:22 UTC, jonilsonds9 requested changes

2022-03-30 22:22 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +    public EntityManager em;
Porque `public`??? Vou pedi mudança nisso, esse cara deve ser privado

2022-03-30 22:22 UTC, jonilsonds9 commented on src/main/webapp/categoriesList.jsp
> +        </tr>
Ainda precisa arrumar a indentação aqui, e o fechamento do `<tr>` precisa ser dentro do `c:forEach`, acho que deveria ser assim:
```
<c:forEach items="${categories}" var="categoria">
        <tr>
            <td>${categoria.id}</td>
            <td>${categoria.name}</td>
            <td>${categoria.code}</td>
            <td>${categoria.icon}</td>
            <td>${categoria.categoryDescription}</td>
            <td id="active-${categoria.id}">${categoria.active}</td>
            <td>${categoria.hexaColor}</td>

            <td><button onclick="statusChange(${categoria.id})">changeStatus</button></td>
            <td><a href="/alterarCategoria?id=${ categoria.id }"><button>EDIT</button></a></td>
        </tr>
</c:forEach>
```

2022-03-31 00:14 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humanDev/dao/CategoryDAO.java
> +    public EntityManager em;
falta de atenção minha!

2022-03-31 12:34 UTC, fabiuhp approved these changes

2022-03-31 12:35 UTC, jonilsonds9 approved these changes

2022-03-31 20:11 UTC, FabianoCarregas commented
semana 7 Done

2022-03-31 20:11 UTC, merged