Semana8
FabianoCarregas/human-dev pull request #8
Opened 2022-04-06 18:53 UTC by FabianoCarregas

2022-04-06 22:08 UTC, jonilsonds9 requested changes

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/Category.java
> +    @NotBlank(message = "Name must not be null or empty")
Essas mensagens deveriam ser em português, use as mensagens de validação do spring

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/Category.java
> +    @NotBlank(message = "Name must not be null or empty")
Replique para outros lugares, porque agora não está mostrando as mensagens em português para o usuário

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/activities/Video.java
>      private String videoUrl;
Acho que o nome das colunas deveriam a partir desse ponto ser os mesmos do atributo, isso vai ser muito importante nas queries, desse jeito vai ser muito mais trabalhoso e confuso nas queries.

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/activities/Video.java
>      private String videoUrl;
Mesma coisa, replicar para os demais lugares

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
Porque essa estrategia??

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categoriesList.jsp
> +                        <a role="button" href="subcategories/&{categoria.code}">
Aqui não deveria ser: `href="subcategories/${categoria.code}"` com `$` no lugar do `&` que você colocou?

2022-04-06 22:08 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categoriesList.jsp
> +            </thead>
Arrumar indentação aqui e remover esse `col-`

2022-04-07 13:24 UTC, jonilsonds9 requested changes

2022-04-07 13:24 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/dtos/CategoryFormDto.java
> +    @Pattern(regexp = "^[a-z0-9-]+$", message = "O código pode ter apenas letras minúsculas, não pode conter acentos, espaços ou caracteres especiais")
Vou pedir mudança aqui, mensagens hardcoded não é aceitável usando o spring que tem pronto a parte de mensagens de validação! Usar o properties de validação do spring aqui!

2022-04-07 13:24 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/dtos/CategoryFormDto.java
> +    @Pattern(regexp = "^[a-z0-9-]+$", message = "O código pode ter apenas letras minúsculas, não pode conter acentos, espaços ou caracteres especiais")
Replicar para todos os outros

2022-04-07 13:26 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categoriesList.jsp
> +                        <a role="button" href="subcategories/&{categoria.code}">
Isso ainda não foi arrumado???

2022-04-07 14:57 UTC, FabianoCarregas commented on src/main/webapp/WEB-INF/views/categoriesList.jsp
> +                        <a role="button" href="subcategories/&{categoria.code}">
Vê se agora atualizou ai

2022-04-07 14:58 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/dtos/CategoryFormDto.java
> +    @Pattern(regexp = "^[a-z0-9-]+$", message = "O código pode ter apenas letras minúsculas, não pode conter acentos, espaços ou caracteres especiais")
Alterado para o message.properties

2022-04-07 15:01 UTC, jonilsonds9 requested changes

2022-04-07 15:01 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/Category.java
> +    @NotBlank
Precisa da mensagem nesses `NotBlank`, você poderia fazer assim no ValidationMessages.properties:
```
javax.validation.constraints.NotBlank.message=Campo obrigatório
```
Dessa forma todos que não tiver uma mensagem definida vai usar esse cara

2022-04-07 16:47 UTC, jonilsonds9 approved these changes

2022-04-07 17:34 UTC, fabiuhp approved these changes

2022-04-07 17:34 UTC, fabiuhp commented on src/main/java/br/com/alura/humandev/entities/Course.java
> +public class Course implements Serializable {
Acredito que o Serializable caiu em desuso desde o Java 5 e além disso parece que aqui é o único lugar que voce tá usando. Se achar válido, pode remover.

2022-04-07 17:34 UTC, fabiuhp commented on src/main/java/br/com/alura/humandev/entities/Subcategory.java
> +public class Subcategory implements Serializable {
Mesmo comentário de antes. Mas agora vi que tem mais de um lugar kkkkk, fica a seu critério deixar ou não.

2022-04-07 18:36 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/entities/Subcategory.java
> +public class Subcategory implements Serializable {
Opa bem observado, eu ja removi aqui ja, vou subir ja no proximo branch correto!

2022-04-07 18:38 UTC, merged