Semana9
FabianoCarregas/human-dev pull request #9
Opened 2022-04-13 12:59 UTC by FabianoCarregas

![Screenshot from 2022-04-13 17-20-58](https://user-images.githubusercontent.com/85910969/163266370-2b321ce3-ef9b-43e0-9914-e35de9b78ecf.png)
![Screenshot from 2022-04-13 17-21-30](https://user-images.githubusercontent.com/85910969/163266379-de553b03-078a-47dc-8aa4-c513fe1a1fd4.png)
![Screenshot from 2022-04-13 17-21-45](https://user-images.githubusercontent.com/85910969/163266381-2b940996-dc58-43b0-95c2-f707513bd6c4.png)
![Screenshot from 2022-04-13 17-21-57](https://user-images.githubusercontent.com/85910969/163266384-e56de3d3-0f0a-481b-b0f5-57a28a89618f.png)
![Screenshot from 2022-04-13 17-22-13](https://user-images.githubusercontent.com/85910969/163266387-f4a8eeea-edbc-4c52-9294-a581fb666537.png)

2022-04-14 13:51 UTC, jonilsonds9 requested changes

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +        return "categories/categoriesList";
Boa quebrar as JSPs em pastas!

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +                              BindingResult result) {
Sobre nomes, sei que é a parte mais díficil, mas nesse CRUD simples, você poderia ter como nome do `getAddCategoryForm` apenas `create`, nesse cara aqui (`addCategory`) poderia ser apenas `save` é o que geralmente é usado nos outros frameworks web de outras linguagens.

Assim o update também seria a mesma coisa, o método que apenas mostra o form no navegador com os dados poderia ter o nome `edit` e o metodo que realmente salva no banco poderia ter o nome `update`.

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));
Boa!

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/java/br/com/alura/humandev/entities/Category.java
> +    }
Acho que não seria apenas trocar pra false né? Tipo se é um toggle, então se tiver false ele tem que virar true, um if ternário aqui seria bom, sei que na view não precisa voltar de false pra true, mas nesse caso o nome `toggleStatus` não é correto, porque ele só troca pra false, seria melhor `deactivate`

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
Precisa mesmo disso aqui?

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categories/categoriesList.jsp
> +                        <td class="active${categoria.id} ">${categoria.active == true ? "Ativa" : "Inativa"} </td>
Você está apenas mostrando não entendi o porque dá classe aqui, poderia ser:
```
<td>${categoria.active == true ? "Ativa" : "Inativa"} </td>
```

2022-04-14 13:51 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/views/categories/categoriesList.jsp
> +<script src="../../../assets/js/scripts.js"></script>
Mesma coisa que falei pro outros seria bacana ver sobre custom tags depois, não vou cobrar aqui, só pra você entender um pouco: https://www.caelum.com.br/apostila-java-web/tags-customizadas-com-tagfiles#criando-minhas-proprias-tags-com-tagfiles

2022-04-14 14:31 UTC, FabianoCarregas commented on src/main/java/br/com/alura/humandev/controllers/CategoryController.java
> +                              BindingResult result) {
Sim ficou mais clean realmente!

2022-04-14 14:31 UTC, FabianoCarregas commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
Acho que não existe mais a necessidade!

2022-04-14 14:32 UTC, FabianoCarregas commented on src/main/webapp/WEB-INF/views/categories/categoriesList.jsp
> +                        <td class="active${categoria.id} ">${categoria.active == true ? "Ativa" : "Inativa"} </td>
https://github.com/FabianoCarregas/human-dev/commit/fa1ff16911a2763f761ec46b1000634dfc7a3a8a

2022-04-14 14:34 UTC, FabianoCarregas commented on src/main/webapp/WEB-INF/views/categories/categoriesList.jsp
> +<script src="../../../assets/js/scripts.js"></script>
Boa Jonilson, eu estou dando uma lida aqui, pra entender e já partir desse principio para os proximos! vlw

2022-04-14 17:28 UTC, jonilsonds9 approved these changes

2022-04-18 16:57 UTC, fabiuhp approved these changes

2022-04-19 12:33 UTC, merged